In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 330.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.4 MB/s eta 0:00:12
   ---------------------------------------- 0.1/15.8 MB 991.0 kB/s eta 0:00:16
   ---------------------------------------- 0.1/15.8 MB 1.0 MB/s eta 0:00:16
   ---------------------------------------- 0.2/15.8 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.2/15.8 MB 1.0 MB/s eta 0:00:16
    --------------------------------------- 0.3/15.8 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.4/15.8 MB 1.1 MB/s eta 0:00:14
   - -------------------------------------- 0.4/15.8 MB 1.2 MB/s eta 0:00:13


ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
random_int_array = np.random.randint(1, 50, 10)
random_int_array

array([44, 23, 23, 45, 45, 48, 25, 32, 14,  4])

In [7]:
np.mean(random_int_array)

30.3

In [19]:
tow_dim_array = np.array([[5,8,6], [7,5,9], [5, 6, 7]])
two_dim = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

In [18]:
towArr = np.add(tow_dim_array, two_dim)
towArr

array([[ 6, 10,  9],
       [11, 10, 15],
       [10, 12, 14]])

In [20]:
new_random_int_array = np.random.randint(1, 100, 20)
condition = new_random_int_array > 50
filtered_arr = new_random_int_array[condition]
filtered_arr

array([85, 60, 75, 92, 88, 87, 91])

In [31]:
np.random.shuffle(new_random_int_array)
new_random_int_array

array([ 9, 20, 50, 88, 12, 60, 23, 85, 87, 22,  4, 41, 46, 75, 91, 22, 92,
       37, 16, 16])